In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [5]:
obj = pd.Series([1,2,3,4,-5])
obj

0    1
1    2
2    3
3    4
4   -5
dtype: int64

In [7]:
obj.values

array([ 1,  2,  3,  4, -5], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
obj2 = pd.Series([4,2,3,5,24], index=['a','b','c','d','e'])
obj2

a     4
b     2
c     3
d     5
e    24
dtype: int64

In [10]:
obj2['a']

4

In [11]:
obj2[['a','a','b']]

a    4
a    4
b    2
dtype: int64

In [12]:
obj[obj>2]

2    3
3    4
dtype: int64

In [13]:
'a' in obj2

True

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [17]:
obj3 = pd.Series(sdata)

In [18]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [28]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [31]:
frame = pd.DataFrame(data) 
frame # Not ordered

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [33]:
pd.DataFrame(frame, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [34]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [35]:
frame2.debt

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [36]:
frame['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [39]:
frame.loc[1]

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [41]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [43]:
import numpy as np
frame2.debt = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [44]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2.debt = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [45]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [46]:
del frame2.eastern

AttributeError: eastern

In [47]:
del frame2['eastern']

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [49]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [50]:
frame3 = pd.DataFrame(pop)

In [51]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [52]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [53]:
pd.DataFrame(pop, index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [54]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [55]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [56]:
index[1]

'b'

In [57]:
labels = pd.Index(np.arange(3))

In [59]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [60]:
labels[2] = 3

TypeError: Index does not support mutable operations

In [61]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [62]:
obj2.index is labels

True

In [63]:
obj2.index == labels

array([ True,  True,  True])

In [64]:
labels.dtype

dtype('int64')

# 5.2

In [65]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [66]:
obj.reindex(['a', 'b', 'c', 'd', 'e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [67]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [68]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [69]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

frame.reindex(['a','b','c','d'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [71]:
frame.reindex(columns = ['Texas', 'Utah', 'California'])

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [73]:
obj = pd.Series(np.arange(5), index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [74]:
new_obj = obj.drop('c')

In [75]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [76]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [77]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [78]:
data = pd.DataFrame(np.arange(15).reshape((5,3)),
                   index = ['a','b','c','d','e'],
                   columns = ['one', 'two', 'three'])
data

one  two  three
a    0    1      2
b    3    4      5
c    6    7      8
d    9   10     11
e   12   13     14

In [79]:
data.drop('a')

one  two  three
b    3    4      5
c    6    7      8
d    9   10     11
e   12   13     14

In [82]:
data.drop(columns=['one','two'])

three
a      2
b      5
c      8
d     11
e     14

In [83]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [84]:
obj[1]

1.0

In [85]:
obj['b']

1.0

In [86]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [87]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [88]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [89]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [93]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data[1:3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [98]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [99]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [100]:
data.iloc[1:3,1:3]

two  three
Colorado    5      6
Utah        9     10

In [102]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [104]:
ser[1]

1.0

In [105]:
ser[-1]

KeyError: -1

In [110]:
ser[(-3):(-1)]

0    0.0
1    1.0
dtype: float64

In [106]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [107]:
ser2[-1]

2.0

In [113]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [114]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [115]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [116]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [117]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [120]:
df1 - df2

b   c    d   e
Colorado  NaN NaN  NaN NaN
Ohio     -3.0 NaN -2.0 NaN
Oregon    NaN NaN  NaN NaN
Texas    -3.0 NaN -2.0 NaN
Utah      NaN NaN  NaN NaN

In [121]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [122]:
df2.loc[1, 'b'] = np.nan

In [123]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [124]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [125]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [126]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [127]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [128]:
arr = np.arange(12.).reshape((3, 4))

In [129]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [130]:
arr[0]

array([0., 1., 2., 3.])

In [131]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [133]:
arr[:,0]

array([0., 4., 8.])

In [139]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [141]:
series = frame.iloc[0]

In [142]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [143]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [144]:
frame.b

Utah      0.0
Ohio      3.0
Texas     6.0
Oregon    9.0
Name: b, dtype: float64

In [146]:
frame - frame.iloc[0]

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [147]:
series = pd.Series(np.arange(3), index = ['b','e','f'])
series

b    0
e    1
f    2
dtype: int32

In [150]:
print(frame)
print(frame + series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN


In [153]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [154]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [160]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [3]:
frame = pd.DataFrame(np.random.randn(4, 3), 
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

frame

b         d         e
Utah    0.704996 -1.425045  0.355502
Ohio    0.477229 -0.027908  0.224915
Texas  -0.240620 -1.891793 -0.536526
Oregon  0.701879 -1.844202  0.505068

In [4]:
np.abs(frame)

b         d         e
Utah    0.704996  1.425045  0.355502
Ohio    0.477229  0.027908  0.224915
Texas   0.240620  1.891793  0.536526
Oregon  0.701879  1.844202  0.505068

In [5]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    0.945616
d    1.863884
e    1.041595
dtype: float64

In [6]:
frame.apply(f, axis=1)

Utah      2.130041
Ohio      0.505138
Texas     1.651172
Oregon    2.546081
dtype: float64

In [7]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [8]:
frame.apply(f)

b         d         e
min -0.240620 -1.891793 -0.536526
max  0.704996 -0.027908  0.505068

In [11]:
format = lambda x: '%.2f' % x # the last % is to format code

In [12]:
frame.applymap(format) # enhanced version of map

b      d      e
Utah     0.70  -1.43   0.36
Ohio     0.48  -0.03   0.22
Texas   -0.24  -1.89  -0.54
Oregon   0.70  -1.84   0.51

In [13]:
frame.applymap(abs)

b         d         e
Utah    0.704996  1.425045  0.355502
Ohio    0.477229  0.027908  0.224915
Texas   0.240620  1.891793  0.536526
Oregon  0.701879  1.844202  0.505068

In [15]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [16]:
sorted(obj)

[0, 1, 2, 3]

In [19]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [20]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [21]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [23]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [24]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [25]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [26]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [28]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [29]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [30]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [31]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [32]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [33]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df.loc['b']

0         1         2
b -0.411216  0.500823 -0.807604
b  0.322753 -0.557513  0.503916

In [34]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [35]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [36]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [37]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [38]:
df.mean(axis=1)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [39]:
df = pd.DataFrame(np.arange(16).reshape((4,4)), 
                  index = ['one', 'two', 'three', 'four'],
                  columns = ['a','b','c','d'])
df

a   b   c   d
one     0   1   2   3
two     4   5   6   7
three   8   9  10  11
four   12  13  14  15

In [40]:
df.cumsum()

a   b   c   d
one     0   1   2   3
two     4   6   8  10
three  12  15  18  21
four   24  28  32  36

In [41]:
df.describe()

a          b          c          d
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [43]:
df.idxmin()

a    one
b    one
c    one
d    one
dtype: object

In [44]:
df.idxmin(1)

one      a
two      a
three    a
four     a
dtype: object

In [45]:
import pandas_datareader.data as web

In [46]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']} # this is a way to define a dict !!!

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()}) # transform a dict to a DataFrame
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [58]:
returns = price.pct_change()
returns.tail() # only output the final 5, like .head()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-04-16 -0.002528  0.007618  0.004778  0.000479
2021-04-19  0.005069 -0.003518 -0.007670  0.002019
2021-04-20 -0.012830  0.037861 -0.001855 -0.003809
2021-04-21  0.002930  0.039013  0.008983 -0.000148
2021-04-22 -0.011685 -0.015813 -0.013086 -0.011063

In [57]:
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2016-04-25       NaN       NaN       NaN       NaN
2016-04-26 -0.006947  0.001814 -0.012857 -0.020756
2016-04-27 -0.062578  0.009324 -0.009720 -0.003248
2016-04-28 -0.030566 -0.022596 -0.020416 -0.020996
2016-04-29 -0.011494 -0.007684 -0.000601  0.002880
...              ...       ...       ...       ...
2021-04-16 -0.002528  0.007618  0.004778  0.000479
2021-04-19  0.005069 -0.003518 -0.007670  0.002019
2021-04-20 -0.012830  0.037861 -0.001855 -0.003809
2021-04-21  0.002930  0.039013  0.008983 -0.000148
2021-04-22 -0.011685 -0.015813 -0.013086 -0.011063

[1258 rows x 4 columns]

In [49]:
returns['MSFT'].corr(returns['IBM'])

0.5341068134024438

In [50]:
returns['MSFT'].corr(returns['GOOG'])

0.7761655330249985

In [51]:
returns['MSFT'].cov(returns['IBM'])

0.00015125005521303758

In [52]:
returns.MSFT.corr(returns.IBM)

0.5341068134024438

In [53]:
returns.MSFT.corr(returns['IBM'])

0.5341068134024438

In [54]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.444120  0.719301  0.655205
IBM   0.444120  1.000000  0.534107  0.496313
MSFT  0.719301  0.534107  1.000000  0.776166
GOOG  0.655205  0.496313  0.776166  1.000000

In [55]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000366  0.000139  0.000238  0.000210
IBM   0.000139  0.000269  0.000151  0.000136
MSFT  0.000238  0.000151  0.000298  0.000225
GOOG  0.000210  0.000136  0.000225  0.000281

In [60]:
returns.corrwith(returns)

AAPL    1.0
IBM     1.0
MSFT    1.0
GOOG    1.0
dtype: float64

In [61]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()

In [62]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [72]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [74]:
obj.isin(['a'])

0    False
1     True
2    False
3     True
4     True
5    False
6    False
7    False
8    False
dtype: bool

In [75]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])

In [80]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [81]:
result = data.apply(pd.value_counts)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [82]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0