Q1. Import numpy as np and see the version

In [4]:
import numpy as np
print(np.__version__)

1.16.2


Q2. How to create a 1D array from 0 to 9?

In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


Q3. How to create a boolean array?

In [6]:
x = np.bool(1)
print(x)
print(np.ones((3,3), dtype=bool))
# OR
print(np.full((3,3), True, dtype=bool))

True
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q4. How to extract items from 1D array?

In [7]:
x = np.arange(10)
print(x[x % 2 == 1])
print(x % 2 == 1)

[1 3 5 7 9]
[False  True False  True False  True False  True False  True]


Q5. How to replace items that satisfy a condition with another value in numpy array? Replace the odd number with -1.

In [8]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q6. Replace items that satisfy a condition without affecting the original array.

In [9]:
arr  = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q7. How to reshape an array?

In [10]:
x = np.arange(10)
print(x.reshape(2,5))
print(x.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


Q8. How to stack two arrays vertically?

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
print(a, b)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q9. Stack two arrays horizontally.

In [14]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q10. How to generate custom sequences in numpy without hardcoding?

In [16]:
a = np.array([1,2,3])
# how to get
arr = np.array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3])

In [17]:
np.hstack([np.repeat(a,3), np.tile(a,2)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

Q11. How to get the common items between two python numpy arrays?

In [18]:
a = np.arange(10)
b = np.arange(5,15,1)
print(f"a and b are {a}, {b}")

a and b are [0 1 2 3 4 5 6 7 8 9], [ 5  6  7  8  9 10 11 12 13 14]


In [19]:
np.intersect1d(a,b)

array([5, 6, 7, 8, 9])

Q12. How to remove from one array those items that exist in another?

In [20]:
a = np.arange(10)
b = np.arange(5,15,1)
print(f"a and b are {a}, {b}")

a and b are [0 1 2 3 4 5 6 7 8 9], [ 5  6  7  8  9 10 11 12 13 14]


In [21]:
np.setdiff1d(a,b)

array([0, 1, 2, 3, 4])

Q13. How to get the positions where elements of two arrays match?

In [22]:
a = np.arange(10)
b = np.tile(np.arange(5),2)
print(f"a and b are {a}, {b}")

a and b are [0 1 2 3 4 5 6 7 8 9], [0 1 2 3 4 0 1 2 3 4]


In [23]:
np.where(a==b)

(array([0, 1, 2, 3, 4], dtype=int64),)

Q14. How to extract all numbers between a given range from a numpy array? Say 5 to 10.

In [24]:
a = np.array([2,6,1,9,3,27])

In [25]:
a[np.where((a > 5) & (a < 10))]

array([6, 9])

In [26]:
a[(a>5) & (a<10)]

array([6, 9])

Q15. How to make a python function that handles scalars to work on numpy arrays? Convert the function below to work on two arrays.

In [27]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

maxx(1,5)

5

In [28]:
a = np.array([1,3,421,3,6134])
b = np.array([324,26,13,4,12346])

def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
    
print(maxx(1,5))

pair_maxx = np.vectorize(maxx)

print(pair_maxx(a,b))

5
[  324    26   421     4 12346]


**Now I switch to the JupyterLab.**

Q16. How to swap two columns in a 2d numpy array?

In [29]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
arr[:,[0,1]] = arr[:,[1,0]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [31]:
arr[:, [1,0,2]] # swap back

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q17. Swap two rows

In [32]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Q18. Reverse the rows of a 2D array

In [34]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q19. Reverse the columns of a 2D array

In [36]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
arr[::-1, ] # same as arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [38]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Q20. Create a 2D array containing random floats between 5 and 10

In [39]:
np.random.uniform(5,10, size=(5,4))

array([[8.15994001, 6.06792314, 6.83324122, 7.33552104],
       [8.71051075, 6.17936781, 6.27468982, 6.28301844],
       [8.63989695, 6.84882174, 6.69551354, 7.66318338],
       [9.07375807, 9.01671276, 5.41368035, 5.28623041],
       [7.61868706, 7.01083581, 8.95200707, 9.14540561]])

In [40]:
# OR
np.random.randint(5,10, size=(5,4)) + np.random.random((5,4))

array([[5.08380416, 7.10707774, 7.54979694, 7.13375284],
       [5.27768765, 8.04446642, 9.19059258, 6.42216416],
       [7.03961122, 9.84700484, 5.19083422, 7.11013721],
       [7.9928329 , 5.44196811, 8.81100554, 9.93891114],
       [7.33169441, 9.63671176, 7.99921349, 9.35258597]])

In [41]:
import os
os.getcwd()

'C:\\Users\\GuoLY'

Q21. Print only 3 decimal places in python numpy array.

In [42]:
rand_arr = np.random.random((5,3))
print(rand_arr)

[[0.37389786 0.98545333 0.66380652]
 [0.59959037 0.4634322  0.83531433]
 [0.18400282 0.13512112 0.51542555]
 [0.13767294 0.39219121 0.09695985]
 [0.42605916 0.33555835 0.99974114]]


In [43]:
rand_arr = np.random.random([5,3])
print(rand_arr)

[[0.38921617 0.3247139  0.6301144 ]
 [0.08803948 0.47405133 0.74146998]
 [0.37510744 0.1813493  0.51847575]
 [0.44443801 0.75551714 0.57767741]
 [0.66643611 0.44879217 0.37593593]]


In [48]:
np.set_printoptions(precision = 3)

In [49]:
print(rand_arr)

[[0.389 0.325 0.63 ]
 [0.088 0.474 0.741]
 [0.375 0.181 0.518]
 [0.444 0.756 0.578]
 [0.666 0.449 0.376]]


Q22. Print a numpy array by suppressing the scientific notation?

In [52]:
np.set_printoptions(precision = 9)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[4.389895556e-04, 2.580448552e-04, 3.132179069e-04],
       [2.612417457e-04, 7.907622036e-04, 3.389650779e-04],
       [4.655771413e-05, 3.709247608e-04, 1.431232054e-04]])

In [55]:
np.set_printoptions(suppress = True)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.000441288, 0.000197518, 0.000141701],
       [0.000150313, 0.000663501, 0.00066777 ],
       [0.000018448, 0.000272595, 0.000381454]])

Q23. Limit the number of items printed in output of numpy array.

In [56]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.set_printoptions(threshold = 6)
print(x)

[ 0  1  2 ... 12 13 14]


Q24. Print the full numpy array without truncating.

In [58]:
print(x)

[ 0  1  2 ... 12 13 14]


In [70]:
import sys
x = np.arange(15)
np.set_printoptions(threshold = 6)
print(x)

np.set_printoptions(threshold = sys.maxsize)
print(x)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Q25. Import datasets with number s and texts keeping the text intact in python numpy.

In [73]:
# import the iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter = ',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

Q26. Etract a particular column from 1d array of tuples.